Travel app
reactplay/react-play pull request #1007
Opened 2023-02-26 21:14 UTC by yung-coder

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

A travel advisor app where we can checkout locations on map by fetching restaurants and hotels

Fixes #419 

# How Has This Been Tested?

It has been tested by me in my local System

# Checklist:

- [✔️ ] I have performed a self-review of my own code
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
- [✔️ ] I have made corresponding changes to the documentation
- [✔️ ] My changes generate no new warnings
- [✔️ ] I have added tests that prove my fix is effective or that my feature works
- [✔️ ] New and existing unit tests pass locally with my changes
- [✔️ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
none

2023-02-27 08:31 UTC, atapas commented
@yung-coder The attached issue to the PR is closed already. Could you please create a new one and attach?

2023-02-27 16:54 UTC, yung-coder commented
> @yung-coder The attached issue to the PR is closed already. Could you please create a new one and attach?

my bad linked wrong issue updated now @atapas

2023-03-05 06:13 UTC, Sachin-chaurasiya requested changes
Left a few comments, thanks

2023-03-05 06:13 UTC, Sachin-chaurasiya commented on src/plays/travel-advisor/styles.css
> +.Main-Contanier {
```suggestion
.main-contanier {

```

2023-03-05 06:13 UTC, Sachin-chaurasiya commented on src/plays/travel-advisor/Readme.md
> +- Language: js
```suggestion
- Language: JavaScript

```

2023-03-05 06:13 UTC, Sachin-chaurasiya commented on src/plays/travel-advisor/styles/dropdown.css
> +select {
@yung-coder , do not directly change the style of the element, I would recommend using class.

2023-03-05 06:13 UTC, Sachin-chaurasiya commented on src/plays/travel-advisor/styles/dropdown.css
> +} */
Remove this.

2023-03-05 07:14 UTC, yung-coder commented
@Sachin-chaurasiya fixed

2023-03-05 07:35 UTC, Sachin-chaurasiya approved these changes
Great work @yung-coder  🙌🏻,
Thanks for the contributions ✨

2023-03-05 13:15 UTC, yung-coder commented
All good to be merged or any more modifications @koustov ....?

2023-03-05 15:43 UTC, Sachin-chaurasiya commented
@yung-coder , Build is failing.
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/59080942/222970586-fccf6157-8f35-4187-92b5-a2386c3ed79f.png">

2023-03-05 15:59 UTC, yung-coder commented
Wait a sec @Sachin-chaurasiya

2023-03-05 18:33 UTC, yung-coder commented
@Sachin-chaurasiya  done

2023-03-05 20:13 UTC, yung-coder commented
@Sachin-chaurasiya  @koustov  fixed linting errors is it again failing build....?

2023-03-06 03:49 UTC, koustov requested changes

2023-03-06 03:49 UTC, koustov commented on src/plays/travel-advisor/styles/dropdown.css
> +.select {
Please prefix the class names with your play name as you have done for `travel-advisor-main-Container

2023-03-06 03:52 UTC, koustov requested changes
As you are using HTTP call (`http://api.openweathermap.org/geo/1.0/direct?q=london&limit=5&appid=9f66153982a275eb857428a4be592907`) to the API, this will not work on preview and production build. You need to find an HTTPS alternative 
![image](https://user-images.githubusercontent.com/7145967/223015715-55745857-0333-4222-9818-562b4fb3bf53.png)

2023-03-06 03:52 UTC, koustov commented
> @Sachin-chaurasiya @koustov fixed linting errors is it again failing build....?

Build is working now

2023-03-07 09:26 UTC, yung-coder commented
@koustov  @atapas  made the required changes ...

2023-03-07 13:36 UTC, koustov commented
> @koustov @atapas made the required changes ...

@yung-coder  The preview build is not showing any data. Am I missing anything?

2023-03-07 13:41 UTC, koustov commented
> > @koustov @atapas made the required changes ...
> 
> @yung-coder The preview build is not showing any data. Am I missing anything?

I realized its working but 
1. It takes some time to load 
2. only for Indian locations
3. actually, first one is loading but second time if I enter another location, its not firing any call

Anyway, I will be merging it now. You can enhance it later also.

2023-03-07 13:41 UTC, merged