Emoji guess game
reactplay/react-play pull request #1008
Opened 2023-02-27 11:38 UTC by rashy10

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
The emoji game was added 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

The required component folder and changes were made 

Fixes # 954

## Type of change
Adding the game

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2023-02-27 11:48 UTC, rashy10 commented
Hi @atapas sir, its failing the cypress run test , I really dont understand what I am supposed to  

this is the error it is showing

Error: Timeout awaiting 'request' for 30000ms

2023-02-27 12:19 UTC, atapas commented
> 

This one you can ignore.

Make sure you have run the linting and formatting commands in read me doc before pushing the code.

2023-02-27 12:26 UTC, rashy10 commented
> > 
> 
> This one you can ignore.
> 
> Make sure you have run the linting and formatting commands in read me doc before pushing the code.

Yes @atapas sir the linting and formatting was done

2023-02-27 15:49 UTC, atapas commented
@rashy10 

Can you please add a cover image

![image](https://user-images.githubusercontent.com/3633137/221611801-f185f5e0-4db2-4453-bb7e-e35be316936f.png)

2023-02-27 15:56 UTC, rashy10 commented
> @rashy10
> 
> Can you please add a cover image
> 
> ![image](https://user-images.githubusercontent.com/3633137/221611801-f185f5e0-4db2-4453-bb7e-e35be316936f.png)

yes sir sure ,but where should i update it 😬is there a link ?

2023-02-27 15:59 UTC, atapas commented
> > @rashy10
> 
> > 
> 
> > Can you please add a cover image
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/3633137/221611801-f185f5e0-4db2-4453-bb7e-e35be316936f.png)
> 
> 
> 
> yes sir sure ,but where should i update it 😬is there a link ?

Read the doc please. All info are in create play document

2023-02-27 18:30 UTC, rashy10 commented
Hi @atapas sir,the cover image has been added

<img width="171" alt="Capture" src="https://user-images.githubusercontent.com/88030710/221651714-6223156d-519e-4db5-b33f-dd332dc48dda.PNG">

2023-03-07 18:32 UTC, koustov requested changes

2023-03-07 18:32 UTC, koustov commented on src/plays/emoji-game/App.css
> +.app {
Try to avoid classname collision by adding your play name as a prefix to it, like
`emoji-game-app`

2023-03-07 18:32 UTC, koustov commented on src/plays/emoji-game/components/buttn.css
> +button.row {
use class selector and play name as prefix

2023-03-07 18:32 UTC, koustov commented on src/plays/emoji-game/components/list.css
> +.play-area {
Use prefix of play name for common name classes

2023-03-07 18:32 UTC, koustov commented on src/plays/emoji-game/styles.css
> +/* enter stlyes here */
Better remove the empty files

2023-03-09 10:26 UTC, rashy10 commented
hi @koustov sir , the mentioned changes were done

2023-03-09 13:10 UTC, atapas commented
@koustov Can you plz unblock the PR if all good?

2023-03-09 14:11 UTC, koustov commented
> @koustov Can you plz unblock the PR if all good?

I am good now.

2023-03-09 14:11 UTC, koustov approved these changes
lgtm

2023-03-09 14:11 UTC, merged