CodeNchill - [#2PlaysAMonth]
reactplay/react-play pull request #1037
Opened 2023-03-04 19:41 UTC by PriteshKiri

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

This play is an application to make you productive during your focus hours.

This app has two main features, one is the music player to play focus/Lofi music and the other is a Pomodoro timer which will help you use your time efficiently.

[#2PlaysAMonth]: codeNchill #988

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-05 06:24 UTC, Sachin-chaurasiya approved these changes
Great work @PriteshKiri  🙌🏻,
Thanks for the contributions ✨

2023-03-05 18:47 UTC, koustov requested changes
Tiny comment

2023-03-05 18:47 UTC, koustov commented on src/plays/codenchill/styles.css
> +::-webkit-scrollbar {
We need to avoid generic pseudo selectors to style specific play. It would impact the platform. Can you avoid this one?

2023-03-05 18:47 UTC, koustov commented on src/plays/codenchill/styles.css
> +.progress {
For class selector, please use play specific name
like `codenchill-progress`

2023-03-08 06:13 UTC, atapas approved these changes

2023-03-08 06:14 UTC, atapas approved these changes

2023-03-08 06:14 UTC, merged