Added Numbers Game Play | 947
reactplay/react-play pull request #1055
Opened 2023-03-10 16:28 UTC by byte-king

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) https://github.com/reactplay/react-play/issues/947

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2023-03-10 16:32 UTC, byte-king commented
@atapas  @koustov

2023-04-20 02:49 UTC, koustov requested changes
- Please try to reduce the cover and background image size. 
- I have given some tiny comments

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/styles.css
> +.play-details {
Use play specific class name 
e.g.: `number-games-play-details`

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/styles.css
> +input {
Do not use pseudo selectors. Use specific class selectors.

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/styles.css
> +.buttons {
Use play specific name

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/styles.css
> +Button {
Do not use pseudo selectors

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/styles.css
> +input::placeholder {
Do not use pseudo selectors

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/styles.css
> +input:focus {
Do not use pseudo selectors

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/styles.css
> +.moves {
Use play specific names

2023-04-20 02:49 UTC, koustov commented on src/plays/the-numbers-game/TheNumbersGame.js
> +  // const [message, setMessage] = useState('Guess a number in the given range');
Please remove commented code

2023-04-20 02:50 UTC, koustov requested changes

2023-04-20 02:50 UTC, koustov commented on src/plays/the-numbers-game/bg.png
I don't see this image being used.

2023-05-27 12:22 UTC, closed without merging