chore: removed create-play; content available on docs site
reactplay/react-play pull request #1098
Opened 2023-04-06 14:44 UTC by supminn

# Description

The documentation on "How to create a play" has been moved from CREATE-PLAY.md to https://docs.reactplay.io/how-to-guides/how-to-create-play/
This PR contains the changes to remove the CREATE-PLAY.md file and change the references to point to the docs site.

- Fixes #1099 

# Checklist:

- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-04-06 14:57 UTC, Sachin-chaurasiya requested changes

2023-04-06 14:57 UTC, Sachin-chaurasiya commented on src/common/header/HeaderNav.jsx
> +                href="https://docs.reactplay.io/How-To-Guides/how-to-create-play"
@supminn, I would recommend moving this URL to const and using it everywhere, so if we are changing the URL, we have to make the change in one place only.

2023-04-06 15:04 UTC, Sachin-chaurasiya commented on src/common/header/HeaderNav.jsx
> +                href="https://docs.reactplay.io/How-To-Guides/how-to-create-play"
> sure, that seems like a better approach.
> 
> One question - On the docs page, I changed the link for `discussions` and added our discord link instead. Should I make this change on these files as well? (I found a few references to discussions such as [https://github.com/reactplay/react-play/discussions/new?category=ideas&title=${idea.title}](https://github.com/reactplay/react-play/discussions/new?category=ideas&title=$%7Bidea.title%7D))

No, I think that is intended to start a new discussion on the repo.

2023-04-06 15:25 UTC, Sachin-chaurasiya requested changes

2023-04-16 06:15 UTC, supminn commented
Hi @atapas 
I have incorporated the changes suggested by @Sachin-chaurasiya 
Could you please provide your review?

2023-04-19 12:39 UTC, atapas commented
@supminn there are a few conflicts to take care.

2023-04-19 13:04 UTC, supminn commented
> @supminn there are a few conflicts to take care.

Thanks, I have resolved them.

2023-04-26 14:56 UTC, Sachin-chaurasiya approved these changes
Great work @supminn  🙌🏻,
Thanks for the contributions ✨

2023-04-26 14:59 UTC, atapas commented
LGTM

2023-04-26 15:00 UTC, atapas approved these changes

2023-04-26 15:00 UTC, merged