fix: replaced className with data attribute
reactplay/react-play pull request #1140
Opened 2023-04-29 10:28 UTC by supminn

# Description

Replaced umami related class names with data attribute values.

2023-04-29 13:43 UTC, Sachin-chaurasiya requested changes
Left a few comments, thanks

2023-04-29 13:43 UTC, Sachin-chaurasiya commented on src/common/activities/ActivityBanner.jsx
> +              data-umami-event="gitub-repo-link"
```suggestion
              data-umami-event="github-button"
```

2023-04-29 13:43 UTC, Sachin-chaurasiya commented on src/common/defaultBanner/DefaultBanner.jsx
> +          data-umami-event="github-repo-link"
```suggestion
          data-umami-event="github-button"
```

2023-04-29 13:43 UTC, Sachin-chaurasiya commented on src/common/header/HeaderNav.jsx
> +                data-umami-event="create-play"
```suggestion
                data-umami-event="create-play-button"
```

2023-04-29 13:43 UTC, Sachin-chaurasiya commented on src/common/header/HeaderNav.jsx
> +              data-umami-event="github-repo-link"
```suggestion
              data-umami-event="github-button"
```

2023-04-30 10:51 UTC, Sachin-chaurasiya requested changes

2023-04-30 10:51 UTC, Sachin-chaurasiya commented on src/common/activities/ActivityBanner.jsx
> +              data-umami-event="gitub-button"
```suggestion
              data-umami-event="github-button"
```

2023-04-30 11:33 UTC, Sachin-chaurasiya commented
@supminn , I was thinking to have all the event's names in a constant, so that we will have a single source of truth, and whenever we want to make any changes we have to do that in one place only. wdyt?

```js
const UMAMI_EVENTS = {
GITHUB_BUTTON : "github-button",
CREATE_PLAY_BUTTON : "create-play-button"
}
```

2023-04-30 11:36 UTC, supminn commented
> @supminn , I was thinking to have all the event's names in a constant, so that we will have a single source of truth, and whenever we want to make any changes we have to do that in one place only. wdyt?
> 
> ```js
> const UMAMI_EVENTS = {
> GITHUB_BUTTON : "github-button",
> CREATE_PLAY_BUTTON : "create-play-button"
> }
> ```

This is a great suggestion. I'll get these changes done..
Do you think the events should be named `github-button` or `github-click`? Since this value would be displayed on the Umami dashboard as an event action.

2023-04-30 11:39 UTC, Sachin-chaurasiya commented
> > @supminn , I was thinking to have all the event's names in a constant, so that we will have a single source of truth, and whenever we want to make any changes we have to do that in one place only. wdyt?
> > ```js
> > const UMAMI_EVENTS = {
> > GITHUB_BUTTON : "github-button",
> > CREATE_PLAY_BUTTON : "create-play-button"
> > }
> > ```
> 
> This is a great suggestion. I'll get these changes done.. Do you think the events should be named `github-button` or `github-click`? Since this value would be displayed on the Umami dashboard as an event action.

We can keep the `github-button`.

2023-04-30 11:47 UTC, Sachin-chaurasiya approved these changes
Great work @supminn 🙌🏻,
Thanks for the contributions ✨

2023-04-30 11:47 UTC, Sachin-chaurasiya commented
@atapas , Please review and merge.

2023-05-08 09:29 UTC, atapas approved these changes

2023-05-08 09:40 UTC, atapas commented
@supminn Build fails

![image](https://user-images.githubusercontent.com/3633137/236791195-22abe2c8-6e90-49c7-9133-cb2a2e992fca.png)

2023-05-08 10:10 UTC, atapas approved these changes

2023-05-08 10:28 UTC, merged