Automating lint testing using husky
reactplay/react-play pull request #1144
Opened 2023-04-30 06:15 UTC by Harsh-Daga

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Automated Code Linting and Testing using Husky and Lint-staged to check for any lint errors before any commit. Used lint-staged to check for lint errors only in the staged files instead of the entire project to save time.

Fixes #1138

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Now every time someone tries to commit, lint-staged will run before any commit. lint-staged will run eslint only on the staged files which will help save a lot of time instead of running it on all the files in the project.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2023-04-30 06:29 UTC, Harsh-Daga commented
Hey @Sachin-chaurasiya,
Could you review this?

2023-05-02 06:03 UTC, atapas commented
@Sachin-chaurasiya @supminn Can you please review this one? We need it soon.

Thanks @Harsh-Daga for putting it together.

2023-05-02 14:11 UTC, supminn requested changes

2023-05-02 16:26 UTC, supminn approved these changes
@Sachin-chaurasiya please review it.

2023-05-11 11:34 UTC, Sachin-chaurasiya approved these changes
Great work @Harsh-Daga  🙌🏻,
Thanks for the contributions ✨

2023-05-14 14:42 UTC, atapas commented
@supminn @Sachin-chaurasiya How did you test it.

2023-06-29 02:46 UTC, atapas commented
@Sachin-chaurasiya Can you merge it if all good?

2023-07-13 14:15 UTC, supminn requested changes
Hi @Harsh-Daga 
I finally found a way to test these changes locally. I have requested a few changes. Could you please get them incorporated?

2023-07-13 14:15 UTC, supminn commented on package.json
> +    "*.+(js|jsx|ts|tsx|json|css|md)": [
```suggestion
    "*.+(js|jsx|ts|tsx)": [
```
Eslint is currently configured to only test and fix for JavaScript and TypeScript files.
We can add corresponding plugins to extend this feature within `.eslintrc.js` file.

2023-07-13 14:15 UTC, supminn commented on .husky/pre-commit
You would need to change the access permissions of this file to `chmod +x`. Otherwise, the pre-commit would be ignored and our purpose is defeated.

2023-08-28 12:23 UTC, closed without merging