Created SECURITY.md
reactplay/react-play pull request #1244
Opened 2023-09-16 16:21 UTC by alishabhale

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2023-09-16 18:20 UTC, priyankarpal requested changes

2023-09-16 18:20 UTC, priyankarpal commented on SECURITY.md
> +** Reporting Security Issues**
just need to change a little bit

``` suggestion
## Reporting Security Issues
```

2023-09-16 18:21 UTC, priyankarpal reviewed
@alishabhale please add issue number to the PR description

2023-09-17 01:47 UTC, alishabhale commented
> @alishabhale please add issue number to the PR description

@priyankarpal  Done. Please review.

2023-09-17 02:17 UTC, priyankarpal commented
> > @alishabhale please add issue number to the PR description
> 
> @priyankarpal Done. Please review.

add issue number here (e.g. fix issue #1242 )

![image](https://github.com/reactplay/react-play/assets/88102392/5761b59e-f5ba-49ea-bb5b-df0978477430)

2023-09-17 10:37 UTC, alishabhale commented
> > > @alishabhale please add issue number to the PR description
> > 
> > 
> > @priyankarpal Done. Please review.
> 
> add issue number here (e.g. fix issue #1242 )
> 
> ![image](https://user-images.githubusercontent.com/88102392/268479022-5761b59e-f5ba-49ea-bb5b-df0978477430.png)

@priyankarpal  Done

2023-09-17 12:12 UTC, priyankarpal commented
@alishabhale you're changing only the PR title, that's good but make sure to add issue number to the PR description.
- also, for documentation-related changes, the PR title will be `docs: create security.md #1242 `
- you can check the Conventional Commits guide it's really useful  https://www.conventionalcommits.org/en/v1.0.0/ 
![image](https://github.com/reactplay/react-play/assets/88102392/c7f97e9e-52e2-4892-8630-51f99ac5f1a5)

2023-09-20 07:11 UTC, priyankarpal requested changes
this discord invite link is not valid

2023-09-20 14:48 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-09-25 06:08 UTC, atapas approved these changes

2023-09-25 06:12 UTC, atapas commented
Thanks @alishabhale for contributing.

2023-09-25 06:12 UTC, merged