Issue 1252
reactplay/react-play pull request #1279
Opened 2023-10-03 14:48 UTC by Abhishek-90

2023-10-03 17:39 UTC, priyankarpal commented
@Abhishek-90 please add the title & description with the issue number next time.

2023-10-03 17:45 UTC, priyankarpal requested changes

2023-10-03 17:45 UTC, priyankarpal commented on .github/workflows/auto-author-assign.yml
> +      -uses: toshimaru/auto-author-assign@v2.0.0
just need to modify 
```suggestion

name: 'Author Assign'

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
```

2023-10-06 00:53 UTC, joshi-kaushal approved these changes
Looks good to me, but we need to check it just after merging.

2023-10-06 00:53 UTC, merged