feat: play search result summary
reactplay/react-play pull request #1350
Opened 2023-10-17 08:04 UTC by janvi01

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Added Search Result Summary.
For example - we searched for "calcu" term. It should show "4 results for plays matching calcu sorted by Newest" below the search bar.

Fixes #1325

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I tested it locally on my development server.

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output
<img width="1792" alt="Screenshot 2023-10-17 at 1 33 39 PM" src="https://github.com/reactplay/react-play/assets/34344234/5cbf250d-9dde-4880-aa1a-394ade85fd82">

2023-10-17 10:09 UTC, priyankarpal requested changes
there are issues with responsiveness 



![image](https://github.com/reactplay/react-play/assets/88102392/280d10d9-c2c3-4877-9f70-13c16539b4c1)

2023-10-18 06:37 UTC, janvi01 commented
@priyankarpal fixed it

2023-10-20 15:42 UTC, janvi01 commented
@atapas Kindly review.

2023-10-31 14:28 UTC, Sachin-chaurasiya reviewed
Left a few comments, thanks

2023-10-31 14:28 UTC, Sachin-chaurasiya commented on src/common/playlists/PlayList.jsx
> +      setGetSearchTerm(new URLSearchParams(location.search).get('text'));
Can we use `useSearchParams` here provided by react-router?

2023-10-31 14:28 UTC, Sachin-chaurasiya commented on src/common/playlists/PlayList.jsx
> +  const [getSearchTerm, setGetSearchTerm] = useState();
```suggestion
  const [searchTerm, setSearchTerm] = useState();
```

2023-10-31 14:28 UTC, Sachin-chaurasiya commented on src/common/playlists/PlayList.jsx
> +      {location.search ? (
```suggestion
      {searchTerm ? (
```

2023-10-31 19:22 UTC, Sachin-chaurasiya approved these changes

2023-10-31 19:22 UTC, Sachin-chaurasiya commented
@priyankarpal , please do the final review and merge it.

2023-11-01 02:59 UTC, priyankarpal approved these changes

2023-11-01 03:04 UTC, merged