feat: improved website accessibility, best practices, seo score to 100%
reactplay/react-play pull request #1421
Opened 2024-01-04 11:12 UTC by janvi01

# Description

The PR aims to improve [reactplay.io](https://reactplay.io/) website accessibility, best practices, seo score to 100% by fixing the warnings/errors given by the lighthouse report. 

some of the warnings fixed are-
1. Elements must meet minimum color contrast ratio
2. Links must have discernible text
3. Links must have descriptive text

(PS: The pr doesn't improve the performance score, will be creating a separate PR for that)

Fixes #1419 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Test locally and the Lighthouse score using google chrome devtools.

# Screenshots or example output

<img width="1792" alt="Screenshot 2024-01-04 at 4 31 13 PM" src="https://github.com/reactplay/react-play/assets/34344234/772de772-647f-4276-93b5-c812c28653d9">

2024-01-05 02:53 UTC, priyankarpal requested changes

2024-01-05 02:53 UTC, priyankarpal commented on src/plays/hangman-game/styled-components.tsx
deployment is failing because of formatting can you revert the formatting? 
![image](https://github.com/reactplay/react-play/assets/88102392/3fc62971-9b3e-42d0-8c34-3738cb635a3e)

2024-01-05 12:26 UTC, priyankarpal approved these changes
Looks Good 🎉

2024-01-15 02:19 UTC, Sachin-chaurasiya approved these changes

2024-01-15 02:20 UTC, Sachin-chaurasiya approved these changes

2024-01-15 02:20 UTC, merged