fix(footer): fixed the overlapping layout issue of browse and create …
reactplay/react-play pull request #1425
Opened 2024-01-22 16:51 UTC by clevercoderjoy

Layout for create and browse button fix for small and medium-sized devices

# Description

Fixed the overlapping create and browse buttons in the footer section for all small and medium-sized devices.

Fixes # (1424)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- This has been tested with the Chrome dev tools responsive view.
- Switched between different devices and checked that the UI was not breaking.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

![image](https://github.com/reactplay/react-play/assets/74505057/28b690dd-a5aa-47d4-a4c9-345bab40870d)
![image](https://github.com/reactplay/react-play/assets/74505057/ba455b66-9ad0-4117-ae72-9a5706bb77e4)

2024-02-09 13:04 UTC, priyankarpal requested changes
There is a conflict error in this branch. Could you take steps to resolve it?

2024-02-11 04:00 UTC, clevercoderjoy commented
> There is a conflict error in this branch. Could you take steps to resolve it?

2024-02-11 04:05 UTC, priyankarpal requested changes

2024-02-11 04:05 UTC, priyankarpal commented on package.json
> +    "open": "^10.0.3",
remove the package 
```suggestion

```

2024-02-11 04:05 UTC, priyankarpal commented on package.json
> +    "plays": "^0.7.0",
remove this too

```suggestion

```

2024-02-11 04:41 UTC, clevercoderjoy commented on package.json
> +    "open": "^10.0.3",
done

2024-02-11 04:41 UTC, clevercoderjoy commented on package.json
> +    "plays": "^0.7.0",
this too done

2024-02-11 04:47 UTC, priyankarpal requested changes
there are little bit issue
![image](https://github.com/reactplay/react-play/assets/88102392/11d53374-73e3-4b01-aeaf-ac322f781976)


![Screenshot_2024-02-11_10-16-47](https://github.com/reactplay/react-play/assets/88102392/9cf131e6-7535-43a7-bb64-0d5983fb19ff)

2024-02-13 03:14 UTC, priyankarpal commented
now it's looking good ✨

2024-02-13 03:16 UTC, priyankarpal submitted a review, later dismissed

2024-02-13 03:16 UTC, priyankarpal commented
@all-contributors add @clevercoderjoy for code

2024-02-17 06:01 UTC, priyankarpal requested changes
everything is messed up. Could you please create a separate PR?

2024-02-18 07:39 UTC, closed without merging