feat:add meetup link icon in the footer
reactplay/react-play pull request #1437
Opened 2024-02-07 13:43 UTC by Meetverma

# Description

Added a meetup link button in the footer

Fixes # 1434

## Type of change
- [Y] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested locally and Works Fine!

# Checklist:

- [Y] I have performed a self-review of my own code
- [Y] My changes generate no new warnings
- [Y] New and existing unit tests pass locally with my changes

# Screenshots or example output
<img width="1236" alt="Screenshot 2024-02-07 at 7 12 35 PM" src="https://github.com/reactplay/react-play/assets/109876335/a3c847d1-60db-41c9-b22d-b8c940e8a91a">

2024-02-14 04:19 UTC, priyankarpal commented
Hello @Meetverma, please refrain from making these types of commits in the future

![header](https://github.com/reactplay/react-play/assets/88102392/0a756078-a578-4198-a323-3b1df57d5497)

2024-02-14 04:25 UTC, priyankarpal requested changes

2024-02-14 04:25 UTC, priyankarpal commented on src/plays/quiz-app/QuizApp.tsx
please fix the formatting issue that's why the building is failing

2024-02-14 04:32 UTC, atapas approved these changes

2024-02-14 10:06 UTC, priyankarpal commented on src/plays/quiz-app/QuizApp.tsx
@Meetverma i will suggest to create new branch for PRs avoid to push from your main branch

2024-02-14 14:14 UTC, priyankarpal commented on src/plays/quiz-app/QuizApp.tsx
for now it's ok but in future create a different branch & the name should be like this `fix-issue-issue-number`

2024-02-15 14:20 UTC, priyankarpal approved these changes

2024-02-15 14:21 UTC, merged

2024-02-15 16:15 UTC, Meetverma commented
Thanks @priyankarpal 
That Was my first commit to react-play...
Looking forward for more contributions :)