feat:add discord icon to header #1443
reactplay/react-play pull request #1444
Opened 2024-02-13 17:25 UTC by clavy123

2024-02-14 03:56 UTC, priyankarpal requested changes
just change the position @clavy123 

![image](https://github.com/reactplay/react-play/assets/88102392/d9040a62-1fd6-4d99-92af-469338575605)

2024-02-14 03:59 UTC, priyankarpal requested changes

2024-02-14 03:59 UTC, priyankarpal commented on src/common/header/header.css
> +  fill: #ffffff;
it should be a discord color `#7289da`

2024-02-14 15:12 UTC, clavy123 commented
@priyankarpal  changes done!!!

2024-02-14 15:12 UTC, priyankarpal commented
> @priyankarpal changes done!!!

yes let me check

2024-02-15 14:04 UTC, priyankarpal commented
hello @clavy123 there is a conflict could you please fix it?

2024-02-15 15:12 UTC, merged