feat(plays): add accordion to play project.
reactplay/react-play pull request #1445
Opened 2024-02-14 02:34 UTC by clavy123

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2024-02-14 04:11 UTC, priyankarpal requested changes

2024-02-14 04:11 UTC, priyankarpal commented on src/plays/accordian/styles.css
> +    }
please don't target `body` directly use another name

2024-02-14 04:11 UTC, priyankarpal commented on src/plays/accordian/Readme.md
> +Update external resources(if any)
remove these lines if you're not using 
```suggestion

```

2024-02-14 15:16 UTC, clavy123 commented
@priyankarpal changes done!!!

2024-02-15 14:40 UTC, priyankarpal approved these changes

2024-02-15 14:41 UTC, merged