Refactor the navbar's social icons
reactplay/react-play pull request #1454
Opened 2024-02-14 12:28 UTC by Shivam-Katare

# Description

Refactor the navbar's social icons code. Removed the repetition part, and instead of that used the mapping to display all icons.

Fixes #1448 

## Type of change

- Code Refactoring

# How Has This Been Tested?

- Tested this change over Chrome Browser and Microsoft Edge

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

# Screenshots or example output

![image](https://github.com/reactplay/react-play/assets/91705825/5474353e-39b4-4ec2-96cf-ab4f3189eef0)

2024-02-14 12:31 UTC, Shivam-Katare commented
@priyankarpal, let me know if any changes are required in it.

2024-02-14 14:18 UTC, priyankarpal requested changes
rename all `link` to `NavLink` @Shivam-Katare

2024-02-14 14:18 UTC, priyankarpal commented on src/common/header/HeaderNav.jsx
> +  const links = [
rename to `NavLinks`
```suggestion
  const NavLinks = [
```

2024-02-14 14:18 UTC, priyankarpal commented on src/common/header/HeaderNav.jsx
> +          {links.map((link, index) => {
```suggestion
          {NavLinks.map((link, index) => {
```

2024-02-14 14:18 UTC, priyankarpal commented on src/common/header/HeaderNav.jsx
> +            const Component = link.type === 'Link' ? Link : link.type;
```suggestion
            const Component = NavLink.type === 'Link' ? Link : NavLink.type;
```

2024-02-14 14:19 UTC, Shivam-Katare commented on src/common/header/HeaderNav.jsx
> +            const Component = link.type === 'Link' ? Link : link.type;
Sure.

2024-02-15 05:29 UTC, Shivam-Katare commented
@priyankarpal, I renamed all `links` to `NavLinks` and also, Rename the `icon` to `Icon` in NavLink mapping to stick to the **PascalCase convention** for JSX components

2024-02-15 06:11 UTC, priyankarpal commented
> @priyankarpal, I renamed all `links` to `NavLinks` and also, Rename the `icon` to `Icon` in NavLink mapping to stick to the **PascalCase convention** for JSX components

thank you

2024-02-15 06:22 UTC, priyankarpal approved these changes
Looks Good 🎉

2024-02-15 13:59 UTC, merged