Feature: Added a play named Random Avatar
reactplay/react-play pull request #1541
Opened 2024-10-09 10:49 UTC by hamzathul

hacktoberfest2024

# Description

This pull request implements a play named Random Avatar generator. The play is a React-based interactive web application that generates random avatars when the "Regenerate" button is clicked.

### Linked Issue:
This pull request addresses and closes Issue #1537  - "[Add a Play]: Random Avatar"

# Conformations:

- The implementation meets the requirements outlined in the issue.
- All features are functioning as expected.
- Code is written in a clear and maintainable way.
- Proper naming conventions are followed.
- Code is properly formatted and adheres to the style guide.
- The README is updated with relevant information about the new features.
- The code contains descriptive commit messages.
- The application works correctly on different screen sizes and devices.

# Screenshots or example output

![Screenshot from 2024-10-09 16-12-48](https://github.com/user-attachments/assets/50d283ab-384e-4e9e-a4ff-1149977613cd)

2024-10-10 14:06 UTC, priyankarpal requested changes

2024-10-10 14:06 UTC, priyankarpal commented on src/plays/random-avatar/styles.css
> +.main {
please change the class name

2024-10-10 14:06 UTC, priyankarpal commented on src/plays/random-avatar/styles.css
> +.circle {
same here change the name

2024-10-10 14:06 UTC, priyankarpal commented on src/plays/random-avatar/RandomAvatar.js
> +              <main className="main">
change the class name to something that's different/related to your project

2024-10-11 04:46 UTC, hamzathul commented
class names are changed


@priyankarpal

2024-10-11 13:40 UTC, priyankarpal approved these changes

2024-10-11 13:41 UTC, merged