Added Selection Sort Visualizer Project in plays folder
reactplay/react-play pull request #1563
Opened 2024-10-20 04:43 UTC by ananya8606

# Selection Sort Visualizer

A **Selection Sort Visualizer** implemented using React. The visualizer allows users to input a series of numbers and watch the step-by-step process of the Selection Sort algorithm as it sorts the array. The interface includes options to add values, sort the array, and reset the visualizer.

## Features

- **Interactive Controls**: Users can add values to the input, trigger the sorting process, and reset the visualizer.
- **Step-by-Step Visualization**: The sorting process is displayed step by step with visual indicators showing the comparisons and swaps.
- **Color-Coded Cues**: Elements being compared are highlighted to make the sorting process easier to follow.

## Type of change

 New feature (non-breaking change which adds functionality)

## Summary of Changes

- Added a new React component-based structure for visualizing Selection Sort.
- Included interactive controls to input values, trigger the sorting process, and reset the visualizer.
- Updated styling to provide visual cues during the sorting process, with color indicators for comparisons and sorted elements.

## Usage

- **Add Values**: Use the input field to add numbers, which will appear in the input visualizer.
- **Sort**: Click the "Sort" button to start the Selection Sort visualization.
- **Reset**: Use the "Reset" button to clear the current state and input a new set of values.

## How It Works

The visualizer performs the Selection Sort algorithm in the following steps:

1. It iterates through the array, finding the minimum element from the unsorted part.
2. It swaps the minimum element with the first unsorted element.
3. The sorted portion is incremented, and the algorithm continues until the entire array is sorted.

During the sorting process:
- Elements being compared are highlighted.
- Sorted elements are displayed in a different color.

## Dependencies

No new dependencies were added for this feature.

## Testing

The testing has been done locally. 
The following tests were performed to verify functionality:

1. **Manual Testing**:
   - Added various values to ensure they are displayed in the input visualizer.
   - Tested the sorting process to confirm the algorithm works as expected, with correct delays and color changes.
   - Used the reset button to ensure the visualizer cleared as expected.

2. **Cross-Browser Testing**:
   - Verified functionality on multiple browsers, including Chrome, Firefox, and Edge.

## To Reproduce the Tests

1. Run the application using `npm start`.
2. Add multiple numbers using the input field.
3. Click "Sort" to observe the sorting process.
4. Use "Reset" to clear the visualizer.

## Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshot of Working Demo

![208376155-4ab58ea9-5139-45d8-b92a-f65835f0598f - frame at 0m39s](https://github.com/user-attachments/assets/f04da2eb-b727-45b7-a28f-27f82518a0d7)
![208376155-4ab58ea9-5139-45d8-b92a-f65835f0598f - frame at 1m1s](https://github.com/user-attachments/assets/4c711162-942a-4ce5-88d5-b68397e871b2)

2024-10-21 04:42 UTC, priyankarpal requested changes
can you link the issue number here? @ananya8606

2024-10-21 04:42 UTC, priyankarpal commented on src/plays/Selection-Sort-Visualizer/select.css
> +}
please avoid targeting directly otherwise it will change the whole website's css

2024-10-21 04:42 UTC, priyankarpal commented on src/plays/Selection-Sort-Visualizer/select.css
> +}
same as above ^^

2024-10-21 04:42 UTC, priyankarpal commented on src/plays/Selection-Sort-Visualizer/select.css
> +.head {
change the class name

2024-10-21 04:42 UTC, priyankarpal commented on src/plays/Selection-Sort-Visualizer/select.css
> +.container {
same as above ^^

2024-10-21 06:07 UTC, ananya8606 commented on src/plays/Selection-Sort-Visualizer/select.css
> +}
resolved

2024-10-21 06:08 UTC, ananya8606 commented on src/plays/Selection-Sort-Visualizer/select.css
> +.container {
resolved

2024-10-24 07:11 UTC, priyankarpal commented
> can you link the issue number here? @ananya8606

@ananya8606 ???

2024-10-24 10:34 UTC, ananya8606 commented
This is a new project.

2024-10-25 04:39 UTC, priyankarpal approved these changes
for now merging the pr but please create an issue first. Then raise a pr when a maintainer assigns you the issue.

2024-10-25 04:40 UTC, merged