Add A New Idea Discussion and remove github finder
reactplay/react-play pull request #220
Opened 2022-05-22 12:34 UTC by Programming-School-Pro-Coding

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/atapas/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Add A New Idea

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-22 12:39 UTC, Programming-School-Pro-Coding commented
@atapas

2022-05-22 14:45 UTC, atapas requested changes

2022-05-22 14:45 UTC, atapas commented on .github/FUNDING.yml
> -custom: ["https://blog.greenroots.info/sponsor", "https://buymeacoffee.com/greenroots", "https://paypal.me/greenrootsinfo"]
This file do not need changes

2022-05-22 14:45 UTC, atapas commented on .github/ISSUE_TEMPLATE/----bug-report---.md
> -Add any other context about the problem here.
This file do not need changes

2022-05-22 14:45 UTC, atapas commented on .github/ISSUE_TEMPLATE/---feature-request---.md
> -Add any other context or screenshots about the feature request here.
This file do not need changes

2022-05-22 14:45 UTC, atapas commented on .github/ISSUE_TEMPLATE/new-play.md
> -## Are you willing to take it up for implementation?
This file do not need changes

2022-05-22 14:45 UTC, atapas commented on .github/pull_request_template.md
>  Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
This file do not need changes

2022-05-22 14:45 UTC, atapas commented on package.json
> +    "styled-components": "^5.3.5",
Why is this added

2022-05-22 14:45 UTC, atapas commented on package.json
> +    "@types/styled-components": "^5.1.25",
Why is this added?

2022-05-22 15:45 UTC, Programming-School-Pro-Coding commented on package.json
> +    "styled-components": "^5.3.5",
I added it when i made github finder

2022-05-22 15:45 UTC, Programming-School-Pro-Coding commented on package.json
> +    "@types/styled-components": "^5.1.25",
I added it when i made github finder

2022-05-22 16:32 UTC, atapas commented on package.json
> +    "@types/styled-components": "^5.1.25",
Ok remove it, now not needed

2022-05-22 16:33 UTC, atapas commented on package.json
> +    "styled-components": "^5.3.5",
Not needed now

2022-05-22 16:34 UTC, Programming-School-Pro-Coding commented on package.json
> +    "styled-components": "^5.3.5",
Ok I fix that

2022-05-29 17:27 UTC, Programming-School-Pro-Coding commented
@atapas please review

2022-05-30 02:40 UTC, atapas commented
@Programming-School-Pro-Coding  Reviewed. It still has changes to many files unnecessarily. Please check the diffs: https://github.com/atapas/react-play/pull/220/files

I really the changes should be in one file PlayIdeas. Could you please revert changes to other files?

2022-05-30 05:12 UTC, atapas commented
Hello @Programming-School-Pro-Coding 

We will be moving the react-play project from the `atapas` account to an organization to help manage the project in a better way. The new organization URL is: https://github.com/reactplay.

> **The movement will take place between 12:30 - 14:00 hrs IST(7:00 am - 8:30 am GMT), 30th May 2022. Please refrain from pushing any changes between this time.**

We will inform you when the movement is complete. You need to make a few minimal configuration changes after that. We will let you know.

2022-05-30 10:48 UTC, Programming-School-Pro-Coding commented
> @Programming-School-Pro-Coding Reviewed. It still has changes to many files unnecessarily. Please check the diffs: https://github.com/atapas/react-play/pull/220/files
> 
> The changes should be in one file PlayIdeas. Could you please revert changes to other files?

Done

2022-05-30 10:48 UTC, Programming-School-Pro-Coding commented
> ### 👷 Deploy Preview for _reactplayio_ processing.
> Name	Link
> 🔨 Latest commit	[5e71f6d](https://github.com/reactplay/react-play/commit/5e71f6da4a26495251d2aaeaf52e0267e6ff6635)
> 🔍 Latest deploy log	https://app.netlify.com/sites/reactplayio/deploys/6294a0ae58074d0008383bef

Ok

2022-05-30 10:49 UTC, atapas commented
> Hello @Programming-School-Pro-Coding
> 
> We will be moving the react-play project from the `atapas` account to an organization to help manage the project in a better way. The new organization URL is: https://github.com/reactplay.
> 
> > **The movement will take place between 12:30 - 14:00 hrs IST(7:00 am - 8:30 am GMT), 30th May 2022. Please refrain from pushing any changes between this time.**
> 
> We will inform you when the movement is complete. You need to make a few minimal configuration changes after that. We will let you know.

The migration is complete. You can find the project here: https://github.com/reactplay

You no need to reclone the project. You just need to set the correct upstream. Here is the link: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork

2022-05-30 10:50 UTC, Programming-School-Pro-Coding commented
> > Hello @Programming-School-Pro-Coding
> > We will be moving the react-play project from the `atapas` account to an organization to help manage the project in a better way. The new organization URL is: https://github.com/reactplay.
> > > **The movement will take place between 12:30 - 14:00 hrs IST(7:00 am - 8:30 am GMT), 30th May 2022. Please refrain from pushing any changes between this time.**
> > 
> > 
> > We will inform you when the movement is complete. You need to make a few minimal configuration changes after that. We will let you know.
> 
> The migration is complete. You can find the project here: https://github.com/reactplay
> 
> You no need to reclone the project. You just need to set the correct upstream. Here is the link: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork

Ok, Please complete review

2022-05-30 10:51 UTC, atapas commented
> > @Programming-School-Pro-Coding Reviewed. It still has changes to many files unnecessarily. Please check the diffs: https://github.com/atapas/react-play/pull/220/files
> > The changes should be in one file PlayIdeas. Could you please revert changes to other files?
> 
> Done

@Programming-School-Pro-Coding You have deleted the files. That's not the right way. If we merge this PR, it will delete those files on main which is incorrect. You had to revert the changes instead.

If the revert is tricky, I would suggest to discard this PR and branch. Create a new branch, do the changes and create a PR.

2022-05-30 10:52 UTC, Programming-School-Pro-Coding commented
Ok, Please a moment

2022-05-30 10:56 UTC, Programming-School-Pro-Coding commented
@atapas Review Again

2022-05-30 11:34 UTC, Programming-School-Pro-Coding commented
@atapas

2022-05-30 11:36 UTC, atapas requested changes
@Programming-School-Pro-Coding Ok let me try explaining it again.

Your changes should be in only 1 file. But if you see, the file changes shows in 5 files. 
![image](https://user-images.githubusercontent.com/3633137/170984080-0ddaf1a0-86ec-463b-a86c-843c57279be6.png)

Other 4 file changes are absolutely not necessary. You may not be syncing your branch from upstream which could be causing this issue.

2022-05-30 11:38 UTC, Programming-School-Pro-Coding commented
> @Programming-School-Pro-Coding Ok let me try explaining it again.
> 
> Your changes should be in only 1 file. But if you see, the file changes shows in 5 files. ![image](https://user-images.githubusercontent.com/3633137/170984080-0ddaf1a0-86ec-463b-a86c-843c57279be6.png)
> 
> Other 4 file changes are absolutely not necessary. You may not be syncing your branch from upstream which could be causing this issue.

You erased .Accidentally attracted Folder

2022-05-30 11:47 UTC, Programming-School-Pro-Coding commented
@atapas

2022-05-30 11:52 UTC, atapas commented
> > @Programming-School-Pro-Coding Ok let me try explaining it again.
> > Your changes should be in only 1 file. But if you see, the file changes shows in 5 files. ![image](https://user-images.githubusercontent.com/3633137/170984080-0ddaf1a0-86ec-463b-a86c-843c57279be6.png)
> > Other 4 file changes are absolutely not necessary. You may not be syncing your branch from upstream which could be causing this issue.
> 
> I deleted .github folder Accidentally

I suggest you close this PR, create fresh new branch from main, do that 1 file change and create a new PR. Tag me in that once you done.

2022-05-30 11:54 UTC, Programming-School-Pro-Coding commented
> > > @Programming-School-Pro-Coding Ok let me try explaining it again.
> > > Your changes should be in only 1 file. But if you see, the file changes shows in 5 files. ![image](https://user-images.githubusercontent.com/3633137/170984080-0ddaf1a0-86ec-463b-a86c-843c57279be6.png)
> > > Other 4 file changes are absolutely not necessary. You may not be syncing your branch from upstream which could be causing this issue.
> > 
> > 
> > I deleted .github folder Accidentally
> 
> I suggest you close this PR, create fresh new branch from main, do that 1 file change and create a new PR. Tag me in that once you done.

Closed

2022-05-30 11:54 UTC, closed without merging