browser back button bug fixed
reactplay/react-play pull request #286
Opened 2022-06-06 06:42 UTC by Deepak8717

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
fixed the bug "wrong route being highlighted when pressed the back button" as  described in issue #284. 

Fixes # (#284 )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

self tested

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2022-06-06 10:36 UTC, Deepak8717 commented
@atapas @koustov please check

2022-06-06 10:41 UTC, atapas commented on src/plays/dynamic-routes/DynamicRoutes.jsx
> +  // eliminate duplicate categories so we can render a navbar of uniq categories
This comment should go above right?

2022-06-06 11:09 UTC, Deepak8717 commented
@atapas  actually that is for github link of react-play on header. which is same or main github repo link for every project.

2022-06-06 14:14 UTC, atapas commented
> @atapas actually that is for github link of react-play on header. which is same or main github repo link for every project. for that we can raise separate issue.

Single line change... related to the same play! Why to create another issue.

got to your play in the play-meta.js file.. change the github link from `https://github.com/reactplay/react-play/tree/main/src/plays/dynamic-routes/:menu` to `https://github.com/reactplay/react-play/tree/main/src/plays/dynamic-routes`... and test it from the preview build.

I hope it helps.

2022-06-09 02:53 UTC, atapas commented
> > @atapas actually that is for github link of react-play on header. which is same or main github repo link for every project. for that we can raise separate issue.
> 
> Single line change... related to the same play! Why to create another issue.
> 
> got to your play in the play-meta.js file.. change the github link from `https://github.com/reactplay/react-play/tree/main/src/plays/dynamic-routes/:menu` to `https://github.com/reactplay/react-play/tree/main/src/plays/dynamic-routes`... and test it from the preview build.
> 
> I hope it helps.

@Deepak8717 where are we on this one?

2022-06-09 05:10 UTC, Deepak8717 commented
@atapas I apologize, for not being able to find any solution.

2022-06-09 06:40 UTC, atapas commented
> @atapas I apologize, for not being able to find any solution.

No worries @Deepak8717 , lets get on it together to find a solution.

2022-06-09 14:49 UTC, Deepak8717 commented
@atapas . i request you to look into this or may be @koustov

2022-06-11 04:25 UTC, koustov commented
@Deepak8717 let's do these steps
1. Got to `play-meta.js`
2. Navigate to your play and change [`path`](https://github.com/reactplay/react-play/blob/8537088890a3d510fd3ab126f717dc2d5e74a878/src/meta/play-meta.js#L386) variable to `/plays/dynamic-routes` instead of `/plays/dynamic-routes/:menu` (note: `path` variable is something dynamically created by application, we shouldn't modify it.)
3. Now on `DynamicRoutes.jsx` read the params
  1. If the param is empty or undefined, set the active route to breakfast
  2. Else, set active routes to what you receive from params

This should solve your issue and will automatically fix the broken `github` link

2022-06-13 03:12 UTC, koustov commented
> @Deepak8717 let's do these steps
> 
> 1. Got to `play-meta.js`
> 2. Navigate to your play and change [`path`](https://github.com/reactplay/react-play/blob/8537088890a3d510fd3ab126f717dc2d5e74a878/src/meta/play-meta.js#L386) variable to `/plays/dynamic-routes` instead of `/plays/dynamic-routes/:menu` (note: `path` variable is something dynamically created by application, we shouldn't modify it.)
> 3. Now on `DynamicRoutes.jsx` read the params
>    
>    1. If the param is empty or undefined, set the active route to breakfast
>    2. Else, set active routes to what you receive from params
> 
> Note: You can also set optional route params in RouteDefs.jsx This should solve your issue and will automatically fix the broken `github` link

@Deepak8717 you can refer [this sample](https://github.com/reactplay/react-play/tree/dynamic-route-rough-cut)

2022-06-14 15:44 UTC, Deepak8717 commented
@koustov thank you so much this helped me a lot. @atapas Kindly review

2022-06-14 17:35 UTC, koustov requested changes
@Deepak8717 you need to pull master. The code is out of sync. Just check the PR, its showing a lot of unnecessary updates

2022-06-15 05:37 UTC, Deepak8717 commented
@koustov please check again

2022-06-15 06:58 UTC, koustov approved these changes
lgtm

2022-06-15 06:59 UTC, atapas approved these changes

2022-06-15 07:00 UTC, merged