Added my new project
reactplay/react-play pull request #298
Opened 2022-06-07 16:22 UTC by mohitdevelops

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-07 16:31 UTC, Programming-School-Pro-Coding commented
> > First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)
> 
> # Description
> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> 
> Fixes # (issue)
> 
> ## Type of change
> Please delete options that are not relevant.
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> # How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
> 
> # Checklist:
> * [x]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [ ]  My changes generate no new warnings
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  New and existing unit tests pass locally with my changes
> * [ ]  Any dependent changes have been merged and published in downstream modules

Please create an issue and see that video to link it

https://user-images.githubusercontent.com/96921717/172433566-61678740-40f0-487b-9426-38d2f766ea18.mp4

2022-06-07 16:34 UTC, Programming-School-Pro-Coding requested changes
Make cover.png as a cover of the template in readme file

2022-06-08 02:55 UTC, mohitdevelops commented
> Make cover.png as a cover of the template in readme file

> Make cover.png as a cover of the template in readme file

I've dropped a cover.png file in the folder

2022-06-09 02:51 UTC, atapas requested changes
@mohitdevelops Some tiny review comments to take care before we merge.

2022-06-09 02:51 UTC, atapas commented on src/plays/product-entry-form/Readme.md
> +# Product entry form
@mohitdevelops Add some more details in the Readme considering some one would like to know how you had implemented this piece. More like a high level article.

2022-06-09 02:51 UTC, atapas commented on src/plays/product-entry-form/components/AddProduct/ProductEntryForm.js
> +	const [inputName, setInputName] = useState("");
I think last time I asked this. Why didn't you handle the state as an object?

2022-06-09 02:51 UTC, atapas commented on src/plays/product-entry-form/components/AddProduct/ProductEntryForm.js
> +		const format = /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/;
Put some comment what this regex does

2022-06-09 02:51 UTC, atapas commented on src/plays/product-entry-form/components/UI/ErrorModal.module.css
> +.modal{
Can you please use this similar prefix `.product-entry-form` for this styles as well?

2022-06-09 06:42 UTC, atapas commented
@mohitdevelops Do we have a issue created for this one?

2022-06-10 01:19 UTC, mohitdevelops commented
> @mohitdevelops Do we have a issue created for this one?

I've updated the request, yes I've also created the issue.

2022-06-10 16:48 UTC, joshi-kaushal requested changes

2022-06-10 16:48 UTC, joshi-kaushal commented on src/plays/product-entry-form/ProductEntryForm.jsx
> +	const ALL_PRODUCTS = [
keep this code in a separate file called `data.js` and import it here. It would be easier to read/debug.

2022-06-10 16:48 UTC, joshi-kaushal commented on src/plays/product-entry-form/ProductEntryForm.jsx
> +	const newProductAdded = function (productLists) {
You could use an arrow function here since you have used it in later code already.

2022-06-10 16:48 UTC, joshi-kaushal commented on src/plays/product-entry-form/ProductEntryForm.jsx
> +					<div>
remove blank div tags.

2022-06-11 04:05 UTC, koustov commented
@mohitdevelops  Is it review-ready? Please mark the comments as 'done' when you have addressed them. 
Also please do the housekeeping (merge master, issue link, PR details update)

2022-06-12 04:43 UTC, atapas commented
@mohitdevelops resolve the merge conflicts and respond to the comments to finish review

2022-06-13 06:56 UTC, closed without merging