Created a Lorem Ipsum Generator Play with React and TailwindCSS
reactplay/react-play pull request #324
Opened 2022-06-18 21:31 UTC by Madflows

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2022-06-19 03:15 UTC, atapas commented
Hi @Madflows please create an issue for this one. Thanks for putting the play.

2022-06-20 09:59 UTC, Sachin-chaurasiya commented
> > Hi @Madflows please create an issue for this one. Thanks for putting the play.
> 
> How?

Hey @Madflows, Please refer to this doc https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue

2022-06-20 11:57 UTC, atapas requested changes

2022-06-20 11:57 UTC, atapas commented on src/meta/play-meta.js
> +    cover: '',
Can you please drop a cover.png file inside your play folder for the thumbnail to appear?

2022-06-22 03:14 UTC, atapas requested changes
@Madflows Review comments

2022-06-22 03:14 UTC, atapas commented on .gitpod.yml
> +# This configuration file was automatically generated by Gitpod.
We don't need to check-in this file.

2022-06-22 03:14 UTC, atapas commented on package.json
> +    "interweave": "^13.0.0",
Could you please provide one-liner for this library?

2022-06-22 03:14 UTC, atapas commented on package.json
> +    "use-clipboard-copy": "^0.2.0",
Do we need a library for it if it is just for copying the text?

2022-06-22 03:14 UTC, atapas commented on src/plays/lorem-generator/Readme.md
> +
Hi @Madflows 

Please provide some more details in the Readme. Consider this as one of the document a beginner will read to get the technical details of your play.

2022-06-22 03:14 UTC, atapas commented on src/plays/lorem-generator/components/Footer/index.jsx
> +            <a href="https://madflows.dev" target={"_blank"} rel="noreferrer">
target blank requires rel attribute.

2022-06-22 03:14 UTC, atapas commented on src/plays/lorem-generator/components/Footer/index.jsx
> +              target={"_blank"}
Same an above about the target blank

2022-06-22 03:14 UTC, atapas commented on src/plays/lorem-generator/components/Main/index.jsx
> +    setQuery("");
This block of code and the one in useEffect can be in a common function?

2022-06-22 03:14 UTC, atapas commented on src/plays/lorem-generator/loremGenerator.css
> +*{
Please do not override anything as global as it will impact other things in the app.

2022-06-22 03:14 UTC, atapas commented on src/plays/lorem-generator/loremGenerator.css
> +
The taolwinf conig already imports these

2022-06-22 03:22 UTC, atapas requested changes
@Madflows A few more comments.

Also, please take care of the responsiveness of the UI.

![image](https://user-images.githubusercontent.com/3633137/174936632-dbef7408-0fef-485b-85b5-45cd1f16d994.png)

2022-06-22 03:22 UTC, atapas commented on src/meta/play-meta.js
> +    cover: '',
We need a cover.png file to show the thumbnail image of your play. Kindly drop one in your play folder and push. Please let me know if you need any help.

![image](https://user-images.githubusercontent.com/3633137/174936139-2b51e093-6df5-4849-8aee-d0cf7b4a9365.png)

2022-06-22 03:22 UTC, atapas commented on src/plays/lorem-generator/components/Footer/index.jsx
> +const Footer = () => {
Are we using this Footer component anywhere? I do not see it.

2022-06-22 03:24 UTC, atapas commented
@Madflows It is a great play. We would love to see it in production ASAP. Please take care of the review comments when you can. Please comment on the "Review Comments" as "Done" as you take care of them. Thanks! Looking forward to getting this in.

2022-06-26 17:46 UTC, atapas commented
Hi @Madflows 

We have some massive changes in the data store and we are changing how the play gets created for a better usability. As this play is interim, we need to make sure it migrates correctly. Could you please ping me on Discord so that I make sure everything is placed?

https://discord.gg/YbmXwU5f

2022-08-03 08:44 UTC, atapas commented
@Madflows Are you working on this?

This PR is in the unresponsive state for long.

2022-08-15 09:27 UTC, atapas commented
Hi @Madflows 

A reminder to get back on this play. This PR may be closed due to a lack of activities soon. Please let us know if you need any help.

Looking forward to getting the play in!

2022-10-01 02:18 UTC, closed without merging

2022-10-01 02:19 UTC, Madflows commented
Time