Added a new play: Markdown Editor
reactplay/react-play pull request #433
Opened 2022-07-29 23:49 UTC by EOEboh

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
I added a new play called Markdown Editor #430 .

It's a beginner-level play which displays input texts as markdown output. It utilizes a dependency called 'remarkable'.

My main motivation is to teach beginners the React library by making them take baby steps before tackling advanced concepts. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

It works perfectly on localhost, netlify, vercel and mobile platforms.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-07-30 07:22 UTC, Sachin-chaurasiya commented
Hey @EOEboh , Thanks for the PR.

In the code, I can see you are using `dangerouslySetInnerHTML` within the div tag.
```
<div className='output-div' dangerouslySetInnerHTML={{__html: md.render(text)}} >
```
Can you avoid this?
Or can we use [tui editor](https://ui.toast.com/tui-editor/) , which will provide both markdown and WYSIWYG mode?

Tui Editor is highly configurable and customisable, with plugin architecture it allows you to add your own plugin and also you can use an existing plugin to add an extra feature to the markdown editor.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/59080942/181879638-1ba19ad6-c4fa-4018-9e3d-ae190b8465f4.png">

cc : @atapas

2022-07-30 07:46 UTC, EOEboh commented
> Hey @EOEboh , Thanks for the PR.
> 
> In the code, I can see you are using `dangerouslySetInnerHTML` within the div tag.
> 
> ```
> <div className='output-div' dangerouslySetInnerHTML={{__html: md.render(text)}} >
> ```
> 
> Can you avoid this? Or can we use [tui editor](https://ui.toast.com/tui-editor/) , which will provide both markdown and WYSIWYG mode?
> 
> Tui Editor is highly configurable and customisable, with plugin architecture it allows you to add your own plugin and also you can use an existing plugin to add an extra feature to the markdown editor.
> 
> <img alt="image" width="1113" src="https://user-images.githubusercontent.com/59080942/181879638-1ba19ad6-c4fa-4018-9e3d-ae190b8465f4.png">
> 
> cc : @atapas

Thanks @Sachin-chaurasiya 
I would check it out.

Quick one: I did a `git reset` yesterday and I couldn't find my play on localhost after pushing changes. Do you have any suggestions how to fix it

2022-08-01 15:16 UTC, EOEboh commented
@atapas can you review this please?

2022-08-01 15:28 UTC, atapas commented
> > Hey @EOEboh , Thanks for the PR.
> > In the code, I can see you are using `dangerouslySetInnerHTML` within the div tag.
> > ```
> > <div className='output-div' dangerouslySetInnerHTML={{__html: md.render(text)}} >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you avoid this? Or can we use [tui editor](https://ui.toast.com/tui-editor/) , which will provide both markdown and WYSIWYG mode?
> > Tui Editor is highly configurable and customisable, with plugin architecture it allows you to add your own plugin and also you can use an existing plugin to add an extra feature to the markdown editor.
> > <img alt="image" width="1113" src="https://user-images.githubusercontent.com/59080942/181879638-1ba19ad6-c4fa-4018-9e3d-ae190b8465f4.png">
> > cc : @atapas
> 
> Thanks @Sachin-chaurasiya I would check it out.
> 
> Quick one: I did a `git reset` yesterday and I couldn't find my play on localhost after pushing changes. Do you have any suggestions how to fix it

@EOEboh Do you still have the issue?

2022-08-01 15:29 UTC, atapas commented
@EOEboh Could you please resolve merge conflicts?

2022-08-01 15:31 UTC, atapas requested changes
Please do not commit this file

src/plays/index.js

2022-08-01 15:36 UTC, atapas requested changes
@EOEboh 

Provided my review comments

2022-08-01 15:36 UTC, atapas commented on src/plays/markdown-editor/Readme.md
> +
Please add more details like,

- What someone will learn from this project?
- You have included an NPM, please mention that in the readme.

2022-08-01 15:36 UTC, atapas commented on src/plays/markdown-editor/styles.css
> +*{
Do not override with *

2022-08-01 15:36 UTC, atapas commented on src/plays/markdown-editor/styles.css
> +  h1, h3{
Do not override selectors.

2022-08-01 15:36 UTC, atapas commented on src/plays/markdown-editor/styles.css
> +  .play-details{
This is a common style across plays.. Please add a unique style and use that.

2022-08-01 15:36 UTC, atapas commented on src/plays/markdown-editor/styles.css
> +  .main{
This is has got higher chances of getting overridden. Please use a unique class name.

2022-08-02 02:42 UTC, atapas requested changes
@EOEboh A few more change requests.

2022-08-02 02:42 UTC, atapas commented on src/plays/index.js
>  // Do not modify the content of this file
@EOEboh as mentioned this file shouldn't be committed.

2022-08-02 02:42 UTC, atapas commented on src/plays/markdown-editor/MarkdownEditor.js
> +      <div className="play-details">
Add a unique class name here along with `play-details`. Like 

```html
<div className="eboh-md-editor play-details">
```

Now use this one as a prefix to the styles in your CSS file. Like
```css
.eboh-md-editor.play-details {


} 

.eboh-md-editor .wrapper-div {

}
// Like the above.
```

2022-08-02 02:42 UTC, atapas commented on src/plays/markdown-editor/MarkdownEditor.js
> +          <div className='output-div' dangerouslySetInnerHTML={{__html: md.render(text)}} >
Do you need the `Remarkable`? As I understand, we are not highlighting any syntax here, so why do we need to treat the output as HTML, why not the plain text?

2022-08-02 02:42 UTC, atapas commented on src/plays/markdown-editor/styles.css
> +  .wrapper-div{
Please follow the structure I mentioned about the unique style name.

2022-08-02 02:42 UTC, atapas commented on src/plays/markdown-editor/styles.css
> +:root {
Please do not override. These selectors are already overridden at the framework root level. So remove.

2022-08-02 02:45 UTC, atapas commented
@EOEboh 

Also please check this error. The build fails due to this



static/css/main.617be5a3.css from Css Minimizer plugin
--
08:04:26.826 | /vercel/path0/static/css/main.617be5a3.css:7170:27: Missed semicolon [webpack://./src/plays/markdown-editor/styles.css:11,4][static/css/main.617be5a3.css:7170,27]

2022-08-02 09:12 UTC, EOEboh commented
@atapas I have made corrections.
However, the conflicting `src/plays/index.js` keeps being pushed despite being in the `.gitignore` file.

Please can you resolve the conflict? Or tell me what to do.

2022-08-02 21:14 UTC, EOEboh commented
@koustov could you have a look, if it's good to go

2022-08-03 03:44 UTC, atapas commented
> @koustov could you have a look, if it's good to go

To me it's almost there. But you need to resolve the conflicts. Just revert the file content back to whatever is in the main.

2022-08-03 03:45 UTC, atapas requested changes

2022-08-03 03:45 UTC, atapas commented on src/plays/markdown-editor/styles.css
> +
use `.md-editor` for rest of the styles too.

2022-08-03 17:50 UTC, atapas commented
@EOEboh Please take a look at my comments.

2022-08-03 19:14 UTC, EOEboh commented
> > @koustov could you have a look, if it's good to go
> 
> To me it's almost there. But you need to resolve the conflicts. Just revert the file content back to whatever is in the main.

What do you really mean here? Can you outline the steps?

2022-08-03 19:35 UTC, koustov commented
I have reviewed and it looks good.
@EOEboh a play got merged, so you need to resolve the conflicts in order to merge

2022-08-03 19:36 UTC, koustov approved these changes
lgtm

2022-08-03 19:37 UTC, EOEboh commented
> I have reviewed and it looks good. @EOEboh a play got merged, so you need to resolve the conflicts in order to merge

I have resolved it now. Please confirm

2022-08-03 19:38 UTC, koustov commented
> > I have reviewed and it looks good. @EOEboh a play got merged, so you need to resolve the conflicts in order to merge
> 
> I have resolved it now. Please confirm

Approved.

2022-08-03 19:39 UTC, EOEboh commented
> > > I have reviewed and it looks good. @EOEboh a play got merged, so you need to resolve the conflicts in order to merge
> > 
> > 
> > I have resolved it now. Please confirm
> 
> Approved.

Feels great to see this lol

2022-08-04 03:35 UTC, koustov commented
Hey @EOEboh , this looks good however do you feel like updating the UI a bit to make it more contemporary? 

You can refer 
- https://dillinger.io/
- https://markdownlivepreview.com/
- https://codebeautify.org/markdown-editor
- https://www.tutorialspoint.com/online_markdown_editor.php

2022-08-04 05:23 UTC, EOEboh commented
> Hey @EOEboh , this looks good however do you feel like updating the UI a bit to make it more contemporary?
> 
> You can refer
> 
> * https://dillinger.io/
> * https://markdownlivepreview.com/
> * https://codebeautify.org/markdown-editor
> * https://www.tutorialspoint.com/online_markdown_editor.php

Sure. I'd work on that

2022-08-05 00:46 UTC, EOEboh commented
@koustov and @atapas  I have modified the UI
I also added a download feature, to download the HTML text output as a pdf file

2022-08-05 03:13 UTC, atapas commented
Thanks for improving it @EOEboh 

Can you please change the text colour of the type here and preview the texts? They are barely readable with black font and brown background. This is a mandatory fix.

Other optional improvement suggestions:

- The boxes can be side by side, then up and down. They should be responsive so that on a small screen, they align column-wise.
- Can provide border-radius to the boxes.
- The Download button can be disabled if there are no texts.
- The cover image design can be better.

Please note that the above comments are optional for you to take care of, but if you do, it will help the play to perceive well. Also, if you think of getting it done and need any help or peer-programming, just let us know in the discord. One of us will work with you.

Thanks.

2022-08-05 10:21 UTC, EOEboh commented
> 

Okay, I'd work on it

2022-08-06 00:33 UTC, EOEboh commented
@atapas I have made corrections and implemented some of your suggestions

2022-08-07 18:08 UTC, koustov commented
> > 
> 
> @atapas Okay, I'd work on it. I just wrote an article about the play, is there a way I can edit the description, and link it?

You can create a link on your play

2022-08-07 18:13 UTC, koustov commented
> @atapas I have made corrections and implemented your suggestions

Hey @EOEboh , me and @atapas  were suggesting on similar lines. Few things are still pending
- A better cover page
- `Type Here` and `Preview` are in black on top of dark back ground which is not readable
- Disable download button when not text in `preview` box
- Make both horizontally aligned and make the most of real estate. something like 
![image](https://user-images.githubusercontent.com/7145967/183305053-a0e46b4f-d20c-4f57-9bf6-7db22a3140ff.png)


Could you please make the changes

2022-08-07 18:16 UTC, EOEboh commented
> > @atapas I have made corrections and implemented your suggestions
> 
> Hey @EOEboh , me and @atapas were suggesting on similar lines. Few things are still pending
> 
> * A better cover page
> * `Type Here` and `Preview` are in black on top of dark back ground which is not readable
> * Disable download button when not text in `preview` box
> * Make both horizontally aligned and make the most of real estate. something like
>   ![image](https://user-images.githubusercontent.com/7145967/183305053-a0e46b4f-d20c-4f57-9bf6-7db22a3140ff.png)
> 
> Could you please make the changes

I already implemented them 🙂

2022-08-07 19:31 UTC, koustov commented
> > > @atapas I have made corrections and implemented your suggestions
> > 
> > 
> > Hey @EOEboh , me and @atapas were suggesting on similar lines. Few things are still pending
> > 
> > * A better cover page
> > * `Type Here` and `Preview` are in black on top of dark back ground which is not readable
> > * Disable download button when not text in `preview` box
> > * Make both horizontally aligned and make the most of real estate. something like
> >   ![image](https://user-images.githubusercontent.com/7145967/183305053-a0e46b4f-d20c-4f57-9bf6-7db22a3140ff.png)
> > 
> > Could you please make the changes
> 
> I already implemented them 🙂

😮 then I am surprised because I didn't see it. Will check again

2022-08-07 19:33 UTC, koustov commented
@EOEboh , looks like latest build didn't get deployed to vercel, it still shows the thumbnail as 
![image](https://user-images.githubusercontent.com/7145967/183307954-a04b158f-5879-4c48-b41b-125a7037502d.png)

and the play as
![image](https://user-images.githubusercontent.com/7145967/183307963-8fad4b54-0942-4c11-a703-27d8bd2f00d1.png)

Will wait for @atapas to fix the vercel issue first

2022-08-09 12:44 UTC, atapas commented
@EOEboh much better looking, great work

@koustov, please conclude.

2022-08-09 14:44 UTC, koustov commented
UI is impressive @EOEboh. I will finish my review by EOD

2022-08-09 17:55 UTC, EOEboh commented
> UI is impressive @EOEboh. I will finish my review by EOD

Thank you @koustov and @atapas .. this means a lot to me.

2022-08-09 18:33 UTC, koustov requested changes
Few observations

2022-08-09 18:33 UTC, koustov commented on package.json
> +    "json-graphql-parser": "^0.0.20",
Let's not downgrade the library.

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/Downloader.jsx
> +import html2canvas from 'html2canvas';
Lets not use `html2canvas` as it brings the style as well

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/Downloader.jsx
> +import html2canvas from 'html2canvas';
also, as its a png/jpg, one cannot copy the text from pdf

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/Downloader.jsx
> +import html2canvas from 'html2canvas';
![image](https://user-images.githubusercontent.com/7145967/183733853-b1497e21-c2bb-4e22-ae5a-7d612ca1fc35.png)

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/MarkdownEditor.js
> +          <Downloader
Need to disable it when no text is rendered. I could download an empty document.

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/MarkdownEditor.js
> +      </h3> */}
Remove commented snippets

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/MarkdownEditor.js
> +          elementId='elementId'
it's very generic id, I would suggest using more specific one like `mde-preview-box`

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/Readme.md
> +- Video:
Lets remove unused properties

2022-08-09 18:33 UTC, koustov commented on src/plays/markdown-editor/styles.css
> +/* enter stlyes here */
Can you run `prettier` on this file? Looks like the alignments are not proper

2022-08-13 04:19 UTC, koustov commented
@EOEboh is it ready for final review?

2022-08-13 09:58 UTC, EOEboh commented
> @EOEboh is it ready for final review?

@koustov I'm sorry I'm delaying, I was down these few days. I would work on the changes today. I apologize

2022-08-13 20:08 UTC, EOEboh commented
@koustov I fixed the issues.

2022-08-14 19:22 UTC, koustov approved these changes
lgtm

2022-08-14 20:03 UTC, EOEboh commented
> lgtm

@koustov I made a small change.
I think everything is set.

2022-08-16 09:52 UTC, atapas approved these changes

2022-08-16 09:57 UTC, merged

2022-08-16 09:59 UTC, atapas commented
@all-contributors please add @EOEboh for Code