Delete plop-create.png
reactplay/react-play pull request #459
Opened 2022-08-06 02:25 UTC by 6km

# Description

Some images are not used since the new play creation workflow

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-07 17:37 UTC, koustov commented
I think neither of the item from `screens` directory being used now and that included `GitHub.png`

2022-08-07 17:38 UTC, koustov requested changes
I think none of the items from `screens` directory is being used now and that included `GitHub.png`
If so, let's remove the entire directory

2022-08-08 18:05 UTC, koustov approved these changes
lgtm

2022-08-09 01:21 UTC, atapas approved these changes

2022-08-09 01:21 UTC, merged