Added New Play - React Gradients
reactplay/react-play pull request #466
Opened 2022-08-07 08:59 UTC by ammaaraslam

# Description

This is a new play consisting of a collection of beautiful gradients that can be copied either as TailwindCSS or CSS code and use in their application. Users are also able to copy each color used in a gradient. This play uses TailwindCSS for styling and one third-part library, `react-hot-toast` for notifications(toasts).
>**Please Note:-** I have used inline CSS in one place to style one thing in the entire play. I've used it for dynamically adding a gradient background to a div. I couldn't quite get it to work with TailwindCSS.

Fixes #442

# Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This play has been tested on my local machine. It creates no new errors and passes all unit tests.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-08-09 05:06 UTC, atapas requested changes
@ammaaraslam A few comments

2022-08-09 05:06 UTC, atapas commented on src/plays/react-gradients/Readme.md
> +
@ammaaraslam I have not seen any play creator has made the readme so extensive and detailed. Thanks a lot. It will help many.

2022-08-09 05:16 UTC, ammaaraslam commented
Hi @atapas. I'll try to fix the changes that you implied. I'll get back with the changes soon!

2022-08-09 07:02 UTC, ammaaraslam commented
Hey @atapas. I have made changes to the play according to your suggestions. Combining the three copy functions into one is a very efficient and a good practice. I didn't think of that when developing, so thanks for pointing that out.
And if you need any other changes to be made, let me know. I'm happy to work with you in this project.

2022-08-09 12:21 UTC, atapas approved these changes
LGTM

2022-08-09 12:28 UTC, atapas commented
@koustov I am good with the changes. Please merge if it looks good to you.

2022-08-09 18:45 UTC, koustov requested changes
a couple of suggestions

2022-08-09 18:45 UTC, koustov commented on src/plays/react-gradients/GradientComponent.js
> +        </GradientCopyButton>
A tooltip on each of the buttons will be great

2022-08-09 18:45 UTC, koustov commented on src/plays/react-gradients/ReactGradients.js
> +          <div className="w-full h-fit pt-14 px-6 flex justify-center items-center text-center">
Do you need to have a footer/credits? as the application itself has a dedicated footer, it doesn't look great to have another one.

2022-08-09 18:46 UTC, koustov commented
@ammaaraslam , the UI is very simple yet elegant.

2022-08-09 23:21 UTC, ammaaraslam commented
Hi @koustov. I'll make the necessary changes you suggested and get back to you soon.

2022-08-10 02:19 UTC, ammaaraslam commented
Hey @koustov, I have made the suggested changes. If there's any more changes that need to be made, let me know.

2022-08-10 05:41 UTC, atapas approved these changes

2022-08-10 13:52 UTC, atapas commented
@koustov you can close this one.

2022-08-10 14:08 UTC, koustov approved these changes
lgtm

2022-08-10 14:09 UTC, merged

2022-08-14 03:51 UTC, atapas commented
@all-contributors please add @ammaaraslam for Code