hackathon banner
reactplay/react-play pull request #561
Opened 2022-09-19 16:33 UTC by nirmalkc

# Description

Hackathon banner design changes for reactplay homepage.

2022-09-22 12:13 UTC, atapas approved these changes

2022-09-22 12:38 UTC, atapas requested changes
It breaks default banner

2022-09-23 12:26 UTC, nirmalkc commented
> It breaks default banner

Fixed it in botth the scenarios.

2022-09-23 13:35 UTC, atapas approved these changes

2022-09-23 13:36 UTC, merged