Quiz app
reactplay/react-play pull request #718
Opened 2022-10-17 17:27 UTC by senali-d

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Build a React application for a quiz play. The quiz should have multiple questions and multiple answers.

Fixes # (#710)

## Type of change

- [x] New Play

# How Has This Been Tested?

This has been tested locally.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-19 18:54 UTC, koustov requested changes
Few ovservations
1. You might want to highlight the question when its hovered and selected
2. Same for options
3. Start Again doesn't work

2022-10-19 20:25 UTC, senali-d commented
> Few ovservations
> 
> 1. You might want to highlight the question when its hovered and selected
> 2. Same for options
> 3. Start Again doesn't work

@koustov Resolved the requested changes.

2022-11-07 13:21 UTC, Angryman18 commented on src/plays/quiz-app/QuizApp.tsx
> +  {qNo: 1, title: 'JavaScript ', question: 'Which type of JavaScript language is ___', answers: ['Object-Oriented', 'Object-Based', 'Assembly-language', 'High-level'], answer: 2, qStatus: 0},
good to have a seperate file for this data

2022-11-07 13:22 UTC, Angryman18 approved these changes
looks good.

2022-11-09 13:46 UTC, atapas commented
@Angryman18 Can you please resolve the conversation so that I can merge?

2022-11-09 13:47 UTC, Angryman18 commented
resolved

2022-11-09 13:51 UTC, merged