Pull request for issue #703
reactplay/react-play pull request #725
Opened 2022-10-18 11:06 UTC by Hat52

# Description

The underline was hiding the text behind. Now it is moved to the back of the text. closes #703 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I have tested the changes by running them on my local.

# Checklist:

- [ ] I have performed a self-review of my own code

2022-10-18 13:40 UTC, atapas reviewed
@Hat52 Check the diff.

There are so many diffs. I am not sure if all are intended.

2022-10-19 06:30 UTC, Hat52 commented
@atapas I think these difference are because of the pretter extension that I have installed in my vs code. It formatted the file.

2022-10-19 18:57 UTC, koustov requested changes
a tiny comment

2022-10-19 18:57 UTC, koustov commented on src/common/playcreated/play-created.scss
> +			// background-color: var(--color-brand-primary);
remove commented code

2022-10-20 18:31 UTC, koustov commented
> @atapas I think these difference are because of the pretter extension that I have installed in my vs code. It formatted the file.

I can see the diffs are beyond prettier changes. Lots of changes around motivation play. Not sure whats going on.

2022-10-21 05:31 UTC, Hat52 commented
> > @atapas I think these difference are because of the pretter extension that I have installed in my vs code. It formatted the file.
> 
> I can see the diffs are beyond prettier changes. Lots of changes around motivation play. Not sure whats going on.

2022-10-21 05:31 UTC, closed without merging