add: calculator play
reactplay/react-play pull request #730
Opened 2022-10-19 01:46 UTC by yashpaddalwar1234

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

This is a calculator app play which would be able to perform basic arithmetic operations

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New Play (non-breaking change which adds functionality)

# How Has This Been Tested?
e2e and local testing
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2022-10-19 03:16 UTC, Angryman18 commented
this is most likely a javascript play not react play.

2022-10-19 05:37 UTC, harshsinghatz commented
> this is most likely a javascript play not react play.

Can you explain a bit more?. Because this play uses JSX and hooks.

2022-10-19 15:58 UTC, Angryman18 commented
> > this is most likely a javascript play not react play.
> 
> Can you explain a bit more?. Because this play uses JSX and hooks.

no its fine. its good. but i see calling document object and modifying realdom at several places.

2022-10-19 16:01 UTC, harshsinghatz commented
> > > this is most likely a javascript play not react play.
> > 
> > 
> > Can you explain a bit more?. Because this play uses JSX and hooks.
> 
> no its fine. its good. but i see calling document object and modifying realdom at several places.

Got it @Angryman18 !, but I guess this should work as well

2022-10-19 18:59 UTC, koustov approved these changes
lgtm

2022-10-20 08:08 UTC, koustov commented
@Angryman18 are you good with this PR?

2022-10-20 15:22 UTC, Angryman18 requested changes

2022-10-20 15:22 UTC, Angryman18 commented on src/plays/calculator-app/CalculatorApp.tsx
> +        <div className='calc-container'>
where is PlayHeader component?

2022-11-13 01:25 UTC, Angryman18 commented
any update @harshsinghatz

2022-12-21 12:25 UTC, closed without merging