Svg color change
reactplay/react-play pull request #755
Opened 2022-10-24 06:00 UTC by Hat52

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
The color of the language logo inside the card now changes on the hover of the card closes #747 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- locally.

# Checklist:

- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings

2022-10-24 06:57 UTC, Sachin-chaurasiya requested changes

2022-10-24 06:57 UTC, Sachin-chaurasiya commented on src/common/playlists/playlist.css
> +}
```suggestion
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='20' height='20' data-name='Layer 1' fill='#2F73BF' viewBox='6 6 36 36'%3E%3Cpath d='M6,6V42H42V6ZM26.9,25H22.21V38.76h-3V25H14.57V22.46H26.9ZM32.29,39a9.42,9.42,0,0,1-4.41-1l.66-2.46a8.29,8.29,0,0,0,3.94,1c1.9,0,3-.89,3-2.22s-.82-2-2.89-2.71c-2.69-.95-4.41-2.39-4.41-4.73,0-2.67,2.23-4.68,5.77-4.68a8.66,8.66,0,0,1,3.91.81l-.71,2.4a7,7,0,0,0-3.26-.78c-1.89,0-2.69,1-2.69,2,0,1.25.94,1.84,3.11,2.67,2.84,1.08,4.2,2.5,4.2,4.84C38.47,36.74,36.49,39,32.29,39Z'/%3E%3C/svg%3E");
}
```

2022-10-24 06:57 UTC, Sachin-chaurasiya commented on src/common/playlists/playlist.css
> +}
```suggestion
.list-plays li a:hover .play-header .language-js{
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='20' height='20' viewBox='0 0 20 20'%3E%3Cpath fill='#EFD81D' fill-rule='evenodd' d='M379.328 7337.432c-1.745 0-2.873-.832-3.423-1.92l1.53-.886c.403.658.926 1.141 1.853 1.141.778 0 1.275-.389 1.275-.926 0-.808-1.078-1.124-1.839-1.45-1.356-.577-2.256-1.302-2.256-2.833 0-1.409 1.074-2.483 2.753-2.483 1.194 0 2.054.416 2.671 1.503l-1.463.94c-.322-.577-.671-.805-1.208-.805-.551 0-.9.349-.9.805 0 .564.349.792 1.155 1.141 1.689.724 2.967 1.293 2.967 3.155 0 1.692-1.329 2.618-3.115 2.618zm-4.328-2.833c0 1.947-1.199 2.976-2.864 2.976-1.504 0-2.405-.575-2.848-1.575h-.026l1.529-1.069c.295.523.561.894 1.205.894.618 0 1.004-.313 1.004-1.252V7328h2v6.599zM364 7339h20v-20h-20v20z' transform='translate(-364 -7319)'/%3E%3C/svg%3E");
}
```

2022-10-24 07:33 UTC, Hat52 commented
@Sachin-chaurasiya I have update the value of blue to its hex value. As the # is not supported in fill so I had to use %23 instead of #.

2022-10-24 07:39 UTC, Sachin-chaurasiya commented
> @Sachin-chaurasiya I have update the value of blue to its hex value. As the # is not supported in fill so I had to use %23 instead of #.
> 

@Hat52 , Typescript and JavaScript colour would be different so use the same hex code that I have suggested.

2022-10-24 08:07 UTC, Hat52 commented
@Sachin-chaurasiya Changed the color of ts.

2022-10-24 08:30 UTC, Sachin-chaurasiya commented
> @Sachin-chaurasiya Changed the color of ts.

@Hat52 , You have added the wrong colour codes, please add the below codes.

- Typescript - #2F73BF
- Javascript- #EFD81D

2022-10-24 08:30 UTC, Sachin-chaurasiya commented on src/common/playlists/playlist.css
> +}
@Hat52 , For Typescript.

2022-10-24 09:47 UTC, Hat52 commented
@Sachin-chaurasiya Done

2022-10-24 10:26 UTC, Sachin-chaurasiya approved these changes

2022-10-29 03:34 UTC, atapas approved these changes

2022-10-29 03:34 UTC, merged