[WIP] Created the banner structure and fixed the styling
reactplay/react-play pull request #877
Opened 2023-01-16 14:58 UTC by aimunhidden485

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description
Added a dynamic banner which will change everytime the page loads

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2023-01-17 10:16 UTC, atapas commented
@aimunhidden485 The build fails with a lot of lint errors

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/3633137/212871773-70c24701-f8dc-4c45-a146-0d2be880ddb5.png">

Please follow the steps in readme to correct those.

2023-01-17 11:28 UTC, aimunhidden485 commented
> @aimunhidden485 The build fails with a lot of lint errors
> 
> <img alt="image" width="1055" src="https://user-images.githubusercontent.com/3633137/212871773-70c24701-f8dc-4c45-a146-0d2be880ddb5.png">
> 
> Please follow the steps in readme to correct those.

okay I'm checking

2023-01-18 15:39 UTC, atapas requested changes

2023-01-18 15:39 UTC, atapas commented on src/common/playlists/DynamicBanner.jsx
> +          minHeight: '70vh'
The banner height is too large and we end up seeing only one row of play. Reduce it to 50vh

![image](https://user-images.githubusercontent.com/3633137/213213881-2587b499-80dc-4d62-8288-43b7254233cc.png)

Also why the inline styles?

2023-01-18 15:39 UTC, atapas commented on src/common/playlists/PlayList.jsx
> +      (play) => all_plays[play.component ? play.component : toSanitized(play.title_name)]
Add a comment for this line of code.

2023-01-18 15:43 UTC, atapas commented
Sometime getting preview not available even of there is a cover image

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/3633137/213217529-e4558a10-c52f-4875-bef8-9cf709e12bd5.png">

2023-01-19 09:24 UTC, aimunhidden485 commented
> Sometime getting preview not available even of there is a cover image
> 
> <img alt="image" width="1494" src="https://user-images.githubusercontent.com/3633137/213217529-e4558a10-c52f-4875-bef8-9cf709e12bd5.png">

Okay I'm checking

2023-01-19 09:25 UTC, aimunhidden485 commented on src/common/playlists/PlayList.jsx
> +      (play) => all_plays[play.component ? play.component : toSanitized(play.title_name)]
okay

2023-01-19 11:10 UTC, aimunhidden485 commented
https://user-images.githubusercontent.com/96931784/213427398-40d04dec-bead-400d-9906-4eff9c6494be.mp4

2023-01-24 03:56 UTC, atapas approved these changes
Tested it with @koustov and it worked well.

2023-01-24 03:58 UTC, atapas commented
Hi @aimunhidden485 Can we not truncate the description here?

![image](https://user-images.githubusercontent.com/3633137/214209488-e63dacc6-a20f-42aa-b81b-e460f6f4d603.png)

Can you please fix this so that I can merge?

2023-01-24 05:00 UTC, aimunhidden485 commented
> Hi @aimunhidden485 Do not truncate the description here?
> 
> ![image](https://user-images.githubusercontent.com/3633137/214209488-e63dacc6-a20f-42aa-b81b-e460f6f4d603.png)
> 
> Can you please fix this so that I can merge?

sure

2023-01-24 07:44 UTC, atapas approved these changes

2023-01-24 07:44 UTC, merged