Created calculator
reactplay/react-play pull request #944
Opened 2023-02-06 13:07 UTC by suryanshsoni120

# Description

A Calculator which can perform basic arithmetic operations.

Fixes #928 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on local system.

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

2023-02-08 14:30 UTC, atapas requested changes
Hey great work! Please take care of the review comments to get t merged.

2023-02-08 14:30 UTC, atapas commented on src/plays/simple-calculator/SimpleCalculator.js
> +        <div className="play-details-body">
Add an additional and unique class name here, say `soni-calc`. We will use it in the CSS files.

2023-02-08 14:30 UTC, atapas commented on src/plays/simple-calculator/styles/Buttons.css
> +.show-btn {
Please use the unique style as a prefix to all the class names here like `.soni-calc .equal`. THis is to reduce the chances of CSS overrides.

2023-02-08 14:30 UTC, atapas commented on src/plays/simple-calculator/styles/Display.css
> +.display {
Same comment as another CSS

2023-02-08 18:43 UTC, suryanshsoni120 commented on src/plays/simple-calculator/Readme.md
> +# Simple Calculator
Sir math.js library is used to perform the calculations.

2023-02-09 16:25 UTC, atapas commented on src/plays/simple-calculator/SimpleCalculator.js
> +        <div className="play-details-body">
Hi @suryanshsoni120, please add the unique class name here and use it to prefix in your CSS file.

2023-02-14 11:01 UTC, atapas commented
Hi @suryanshsoni120 Please catch me on discord as I still see the review comments opened about the style override. I can explain to you over a quick call.

2023-02-17 18:10 UTC, atapas commented
@suryanshsoni120 Please add the video link

2023-02-18 15:47 UTC, atapas commented
> @suryanshsoni120 Please add the video link

@suryanshsoni120 any update?

2023-02-25 16:02 UTC, atapas commented
> > @suryanshsoni120 Please add the video link
> 
> @suryanshsoni120 any update?

@suryanshsoni120 will you please add the recording? Your good work will get merged.

2023-02-27 06:24 UTC, atapas commented
@suryanshsoni120 I am merging your play. But it is still missing the video recording. Please update the video link before 28th Feb 2023 end of the day for it to be qualified for the event.

2023-02-27 06:27 UTC, atapas approved these changes

2023-02-27 06:27 UTC, merged