Object detect with tenserflowjs
reactplay/react-play pull request #998
Opened 2023-02-23 20:57 UTC by senali-d

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/reactplay/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

Object detection using AI model. Here I use TensorFlow.js library.

Fixes # (#952)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Locally tested.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-02-24 11:03 UTC, atapas requested changes

2023-02-24 11:03 UTC, atapas commented on src/plays/object-detector/Readme.md
> +
You have added new libraries. Please list about them with why?

2023-02-24 11:03 UTC, atapas commented on src/plays/object-detector/Readme.md
> +Build a play for detect objects with ai model
It is an interesting project. Could you please elaborate about it?

2023-02-24 12:46 UTC, senali-d commented
@atapas Resolved the requested changes.

2023-02-25 04:49 UTC, atapas approved these changes

2023-02-25 05:03 UTC, merged